# Generated by Django 2.1.2 on 2018-10-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('text_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('question_answer', models.TextField()),
                ('question_owner', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
