# Generated by Django 2.1.2 on 2018-10-28 02:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
