# Generated by Django 2.1.2 on 2018-10-28 06:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name_en', models.CharField(max_length=100)),
                ('chapter_no', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=150)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name_bn', models.CharField(max_length=100)),
                ('language_name_en', models.CharField(max_length=100)),
                ('slogan_top', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, upload_to='uploads/tutorials/')),
            ],
        ),
    ]
